DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS categories;

CREATE TABLE IF NOT EXISTS users (
  users_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  users_email VARCHAR(64) NOT NULL,
  users_name VARCHAR(256) NOT NULL,
  CONSTRAINT pk_users PRIMARY KEY (users_id),
  CONSTRAINT uq_user_email UNIQUE (users_email)
);

CREATE TABLE IF NOT EXISTS categories (
  categories_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  categories_name VARCHAR(64) NOT NULL,
  CONSTRAINT pk_categories PRIMARY KEY (categories_id),
  CONSTRAINT uq_category_name UNIQUE (categories_name)
);